name: Build project
description: Install dependencies, build and test project

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version: '22'
    - name: Installing dependencies
      run: npm ci
      shell: bash
    - name: Run linter
      run: npm run lint
      shell: bash
    - name: Build project
      run: npm run build
      shell: bash
    - name: Running e2e tests
      run: npm test
      shell: bash
