name: Build project
description: Install dependencies, build and test project

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Installing dependencies
      run: npm ci
      shell: bash
    - name: Build project
      run: npm run build
      shell: bash
    - name: Running e2e tests
      run: npm test
      shell: bash
