name: Build project
description: Install dependencies, build and test project

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version: '22'
    - name: Installing dependencies
      run: npm ci
      shell: bash
    # TODO Restore before merge
    # - name: Run linter
    #   run: npm run lint
    #   shell: bash
    - name: Build project
      run: npm run build
      shell: bash
    # TODO Restore before merge
    # - name: Running e2e tests
    #   run: npm test
    #   shell: bash
