name: AI Instructions Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 3' # Every Wednesday at 8am UTC

jobs:
  sync:
    if: false
    uses: empathyco/platform-reusable-github-actions/.github/workflows/ai-instructions-sync.yml@bb77254a21ec4b044e311f546e183adbe24e3ec4 # main
    secrets: inherit
