name: AI Instructions Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 3' # Every Wednesday at 8am UTC

jobs:
  sync:
    if: false
    uses: empathyco/platform-reusable-github-actions/.github/workflows/ai-instructions-sync.yml@a3a73bcada87ffcc89da9f9dc251050c5bab7a09 # main
    secrets: inherit
