name: Build on push
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ci-pr:
    runs-on: [self-hosted, linux, x64, vm, docker, big, frontend]
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install deps, lint, build and test project
        uses: ./.github/actions/install
